#!/bin/bash

echo 'Install zsh'
echo '-----------'
brew install zsh

# Install zsh
echo 'Install oh-my-zsh'
echo '-----------------'
rm -rf $HOME/.oh-my-zsh
curl -L https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh | sh
mkdir ~/.oh-my-zsh

# Add global gitignore
ln -s $HOME/dotfiles/shell/.global-gitignore $HOME/.global-gitignore
git config --global core.excludesfile $HOME/.global-gitignore

# Symlink zsh prefs
rm $HOME/.zshrc
ln -s $HOME/dotfiles/shell/.zshrc $HOME/.zshrc

# Symlink the Mackup config
ln -s $HOME/dotfiles/macos/.mackup.cfg $HOME/.mackup.cfg

# Fix missing font characters (see https://github.com/robbyrussell/oh-my-zsh/issues/1906)
cd ~/.oh-my-zsh/themes/
git checkout d6a36b1 agnoster.zsh-theme

# Activate z
cd ~/dotfiles/shell
chmod +x z.sh

echo 'Install nvm'
echo '-----------'
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.37.2/install.sh | bash

echo 'Install homebrew'
echo '----------------'
echo install homebrew
sudo rm -rf /usr/local/Cellar /usr/local/.git && brew cleanup
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"

echo 'Install some nice quicklook plugins'
echo '-----------------------------------'
brew install --force qlcolorcode qlstephen qlmarkdown quicklook-json qlprettypatch quicklook-csv betterzip webp-quicklook suspicious-package

echo 'Install php'
echo '-----------'
brew install php@5.6
brew install php@7.1
brew install php@7.3
brew install php@7.4
brew install php@8.0

echo 'Install imagemagick'
echo '-------------------'
brew install imagemagick

echo 'Install imagick'
echo '---------------'
pecl install imagick

#echo 'Install redis'
#echo '-------------'
#pecl install redis

#echo 'Install yarn'
#echo '------------'
#brew install yarn

echo 'Install zsh-autosuggestions'
echo '---------------------------'
brew install zsh-autosuggestions

echo 'Install mamp'
echo '------------'
brew install mamp

echo 'Install composer'
echo '----------------'
brew install composer

echo 'Install 1password'
echo '-----------------'
brew install 1password

echo 'Install sublime-text'
echo '--------------------'
brew install sublime-text

echo 'Install tableplus'
echo '-----------------'
brew install tableplus

echo 'Install tinkerwell'
echo '------------------'
brew install tinkerwell

echo 'Install fork'
echo '------------'
brew install fork

echo 'Install termius'
echo '---------------'
brew install --cask termius

echo 'Install slack'
echo '-------------'
brew install slack

echo 'Install telegram'
echo '----------------'
brew install telegram

echo 'Install shadow'
echo '--------------'
brew install shadow

echo 'Install spotify'
echo '---------------'
brew install spotify

echo 'Install whatsapp'
echo '----------------'
brew install whatsapp

echo 'Install transmit'
echo '----------------'
brew install transmit

echo 'Install atom'
echo '------------'
brew install atom

echo 'Install google-drive-file-stream'
echo '--------------------------------'
brew install google-drive-file-stream

echo 'Install postman'
echo '---------------'
brew install postman

echo 'Install anydesk'
echo '---------------'
brew install anydesk

echo 'Install authy'
echo '-------------'
brew install authy

echo 'Install ansible'
echo '---------------'
brew install ansible

echo 'Install discord'
echo '---------------'
brew install discord

echo 'Install teleport https://gravitational.com/teleport'
echo '---------------------------------------------------'
brew install teleport

echo 'Install screen.so'
echo '-----------------'
brew install --cask screen

echo 'Install firefox'
echo '---------------'
brew install --cask firefox

echo 'Install zoom'
echo '------------'
brew install --cask zoom

echo 'Install iterm2'
echo '--------------'
brew install --cask iterm2

echo 'Install google-chrome'
echo '---------------------'
brew install --cask google-chrome

echo 'Install figma'
echo '---------------------'
brew install --cask figma

echo 'Install visual studio code'
echo '---------------------'
brew install --cask visual-studio-code

echo 'Install deadbolt encryption tool
echo '-------------------------------'
brew install --cask deadbolt

echo 'create ~/.nvm directory'
echo '-----------------------'
mkdir ~/.nvm

echo 'create ~/.profile directory'
echo '-----------------------'
mkdir ~/.profile

echo '++++++++++++++++++++++++++++++'
echo '++++++++++++++++++++++++++++++'
echo 'All done!'
echo 'Things to do to make the agnoster terminal theme work:'
echo '1. Install menlo patched font included in ~/dotfiles/misc https://gist.github.com/qrush/1595572/raw/Menlo-Powerline.otf'
echo '2. Install patched solarized theme included in ~/dotfiles/misc'

echo '++++++++++++++++++++++++++++++'
echo 'Some optional tidbits'

echo '1. Make sure dropbox is running first. If you have not backed up via Mackup yet, then run `mackup backup` to symlink preferences for a wide collection of apps to your dropbox. If you already had a backup via mackup run `mackup restore` You'\''ll find more info on Mackup here: https://github.com/lra/mackup.'
echo '2. Set some sensible os x defaults by running: $HOME/dotfiles/macos/set-defaults.sh'
echo '3. Make a .dotfiles-custom/shell/.aliases for your personal commands'

echo '++++++++++++++++++++++++++++++'
echo 'Some missing apps'

echo '- FileMaker'
echo '- Pixelmator'
echo '- PhpStorm'

echo '++++++++++++++++++++++++++++++'
echo '++++++++++++++++++++++++++++++'

echo '++++++++++++++++++++++++++++++'
echo 'Font Awesome v5 Pro global license'

echo 'Log-in (using credentials in 1Password) at: https://fontawesome.com/v5.15/how-to-use/on-the-web/setup/using-package-managers'
echo 'read the "Installing the Pro version of Font Awesome" instructions'
echo 'example: '
echo 'npm config set "@fortawesome:registry" https://npm.fontawesome.com/'
echo 'npm config set "//npm.fontawesome.com/:_authToken" XXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXXX (see above link)'

echo '++++++++++++++++++++++++++++++'
echo '++++++++++++++++++++++++++++++'
